# Generated by Django 2.2.2 on 2020-07-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'много видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='hi', help_text='слаг должен быть уникальным', verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='showvideo.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='нравится)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='urls',
            field=models.URLField(verbose_name='Урл, понял?'),
        ),
    ]
